### ISSUE TITLE
Add background image in the Loading addresses screen

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet#106]
Other initial screens:
![image](https://user-images.githubusercontent.com/3298774/79532141-9a20d680-804a-11ea-8c1d-ad35cf9717be.png)

Loading addresses screen:
![image](https://user-images.githubusercontent.com/3298774/79532181-bde41c80-804a-11ea-8ae3-e788902fe9f3.png)

**Comment by intyro** [comment]
I'll pick this one.

**Comment by jansegre** [comment]
Go ahead, feel free to ask for help getting around the project.

**Comment by obiyankenobi** [comment]
Closed on #109
