### ISSUE TITLE
UnhandledRejection

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet#117]
It seems we are not handling the exception raised when the wallet tries to get the full node version. I don't know exactly what happens in the user interface.

Link: https://sentry.io/organizations/hathor/issues/1064788860/?project=1410476&query=is%3Aunresolved&statsPeriod=7d

**Comment by pedroferreira1** [comment]
This issue is connected to https://github.com/HathorNetwork/hathor-wallet/issues/115.

The blank screen generates the `UnhandledRejection`.

When issue #115 is fixed, this will be solved.
