### ISSUE TITLE
Wallet doesn't load history

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-wallet#120]
Discord user Dustin reported that a friend was having problems with his wallet. The history was not being loaded, just realtime transactions/blocks showed up.

I checked on the explorer and the address had over 4000 transactions. Actually, all blocks as this wallet was being used for mining.

He reported the wallet app was loading normally. I asked him to change to node2 (which is located in the US) and that eventually solved the problem.

What is weird about this bug is that the user should not get past the 'wallet loading' screen before loading all transactions.

**Comment by jansegre** [comment]
This seems to have been resolved when we fixed the CPU usage bug.

**Comment by obiyankenobi** [comment]
Talked to Dustin yesterday and he reported his friend hasn't had any more problems. Likely resolved after the high CPU usage was solved.
