### ISSUE TITLE
Wallet request fails have gotten much more frequent

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-wallet#124]
Dustin reported this to me. And this is happening with my wallet too, I just had assumed it was my internet link failing again, but apparently it happens regardless of my link.

When opening the wallet, it takes a while (maybe a few minutes) and more frequently than not the "request failed" pop appears. I'll usually just retry it, but it can happen repeatedly.

It appears have more impact on wallets with more transactions. Maybe specifically wallet with a lot of transactions on a single (or few) addresses.

**Comment by pedroferreira1** [comment]
I've noticed that also on my wallets (with not so many transactions). However I think this is also happening on the explorer, it's usually taking too long to reply to some requests. I've associated to the high use of CPU of our nodes, which could be the problem in both cases.

**Comment by jansegre** [comment]
I haven't had any fails after we fixed CPU usage. It's been working well for Dustin too.
