### ISSUE TITLE
Problem downloading new wallet v0.17.0 on Windows

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet#138]
> I tried to download the windows wallet from the website and when it downloads on my computer, it throws an error in the download box. red caution triangle and instead of being able to "open and run program" it says "discard" instead.

OS: Windows
Browser: Google Chrome
Info: He tried to download from our website and after directly from github and the same problem happened. I sent him the link to download the previous version (v0.15.0) and it worked.
![image](https://user-images.githubusercontent.com/3298774/91383084-aa6b6e00-e801-11ea-81cf-fde6dafade3f.png)

**Comment by msbrogli** [comment]
![Screen Shot 2020-08-27 at 9 57 58 AM](https://user-images.githubusercontent.com/449119/91472100-db709080-e84b-11ea-96ce-b1a73f2b5158.png)

**Comment by msbrogli** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview

**Comment by msbrogli** [comment]
I guess it is related to the type of Signing Code Certificate we bought.

Take a look here: https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

**Comment by msbrogli** [comment]
It seems that nobody has complained about it. Maybe it was just related to our fresh code signing certificate. I think we can close this issue in 15 days if no new report shows up.

**Comment by msbrogli** [comment]
We can reopen this issue if it happens again.
