### ISSUE TITLE
Improve words backup validation UX

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet#150]
We could do something similar to the mobile wallet.

**Comment by thr0wn** [comment]
Hi @pedroferreira1, as you suggested to do something similar to the mobile wallet, I will proceed with the following idea:
![backup-words](https://user-images.githubusercontent.com/5104565/100472159-77fc3600-30ba-11eb-8ca1-cf074df01135.gif)

It follows this Figma prototype: https://www.figma.com/proto/WJoY0LAp2uhcZvfIsMVXPE/Hathor?node-id=2%3A43&scaling=min-zoom.

**Comment by msbrogli** [comment]
@thr0wn Nice prototype. Approved.

**Comment by thr0wn** [comment]
Closed by #159
