### ISSUE TITLE
Wallet does not reset network when resets its data

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet#164]
PRs:
1. https://github.com/HathorNetwork/hathor-wallet/pull/165
2. https://github.com/HathorNetwork/hathor-wallet-lib/pull/136

The bug consists on resetting the wallet when you are connected to a testnet server. When we reset all data, even the server is erased, then we use one of the default servers, which is a mainnet server. But the network does not reset and when starting a new wallet or importing a wallet, we don't call `checkApiVersion` (which is wrong).

To fix the bug we should call `checkApiVersion` when starting the wallet from a reset.

Besides that, I think we shouldn't erase the server when resetting the wallet. If a user is using the testnet and wants to change the wallet, it should continue using the testnet and not force him to change the server again.

The reason we are erasing the server now is because of an old bug we used to have on the wallet desktop, where the wallet screen became white if the server you were connected to was down (e.g. you were connected to a private net that is down now). So we allowed the user to reset the wallet and we had to reset the server to use our default ones.

So this issue becomes two different issues:

1. Wallet desktop issue: call `checkApiVersion` when starting the wallet from a reset.
2. Stop erasing the server when resetting the wallet.

I think 1. is required but 2. depends on the behaviour we want to give to a "Reset wallet". What do you think @msbrogli @andreabadesso @thr0wn @jansegre?

**Comment by msbrogli** [comment]
I agree that we should call `checkApiVersion` when starting the wallet from a reset. Actually, we should call `checkApiVersion` every time we reconnect to the server.

**Comment by msbrogli** [comment]
I agree with keeping the configured server after the reset. In the future, we can create a network reset method if needed.

**Comment by jansegre** [comment]
I agree. I also think we could have a build-time hard-coded default settings. So we can build a wallet that always defaults to the testnet (or mainnet) when it is completely reset. This isn't too important for the desktop wallet, but seems much more useful for the mobile wallet, where a complete reset is really easy to make from the system, and in that case we have no way to keep any settings, so having a build-time default would make the wallet always keep the same network it was built for.
