### ISSUE TITLE
feat: add support for NFT

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet#213]
Suggestion screens:

## Image 1
![image](https://user-images.githubusercontent.com/3298774/131015411-371380f5-0c15-4654-9a57-146ba64ce129.png)

## Image 2
![image](https://user-images.githubusercontent.com/3298774/131015444-1453c24d-f67b-4805-8863-c44b48cea220.png)

## Image 3
![image](https://user-images.githubusercontent.com/3298774/131015460-0babd80b-c122-4c08-b044-2024e135b8dc.png)

**Comment by andreabadesso** [comment]
Screens look good to me
