### ISSUE TITLE
Create new build with Ledger enabled

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-wallet#216]
Branch: dev

Enable ledger prior to build. To do this, set `LEDGER_ENABLED` to `true`.

## Acceptance criteria
- [x] Create a release to build a wallet working with ledger
- Have builds for:
    - [x] Windows
    - [ ] Mac
    - [x] Linux

**Comment by msbrogli** [comment]
Windows:
- exe: https://hathor-public-files.s3.amazonaws.com/ledger-review/Hathor%20Wallet%20Setup%200.19.1-ledger.exe
- exe.blockmap: https://hathor-public-files.s3.amazonaws.com/ledger-review/Hathor%20Wallet%20Setup%200.19.1-ledger.exe.blockmap

Linux:
- AppImage: https://hathor-public-files.s3.amazonaws.com/ledger-review/Hathor%20Wallet-0.19.1-ledger.AppImage
- Deb: https://hathor-public-files.s3.amazonaws.com/ledger-review/hathor-wallet_0.19.1-ledger_amd64.deb

**Comment by msbrogli** [comment]
Mac:
- dmg: https://hathor-public-files.s3.amazonaws.com/ledger-review/Hathor%20Wallet-0.19.1-ledger.dmg
- dmg.blockmap: https://hathor-public-files.s3.amazonaws.com/ledger-review/Hathor%20Wallet-0.19.1-ledger.dmg.blockmap
