### ISSUE TITLE
Scrolling in HTR wallet on desktop

### ISSUE THREAD

**Issue by DAG1234567** [HathorNetwork/hathor-wallet#226]
Hi. I’m using hathor wallet on desktop and recently added a bunch of NFTs and registered those NFTs. These registered and FTEs show up individually on the left-hand side of the screen vertically and sequentially as they are registered one on top of the other. The issue that I’m having is once I register about 10 or so it’s impossible to scroll down any further and see the rest of my NFTs. On the mobile wallet there is zero issue but on the desktop version is where this issue appears. Maybe someone has a fix this problem or has figured a way to scroll on the desktop?

**Comment by DAG1234567** [comment]
Anyone actually looking at this thread and trying to fix problems with the wallet? Or am I just posting here in vain?

**Comment by trondbjoroy** [comment]
> Anyone actually looking at this thread and trying to fix problems with the wallet? Or am I just posting here in vain?

The team replied to this question in the discord a couple of days ago: We are aware of the situation and it’s in our pipeline to fix this issue soon

**Comment by pedroferreira1** [comment]
@DAG1234567 thanks for reporting. As @trondbjoroy said, we are aware of the bug and the next release should have a fix.

**Comment by pedroferreira1** [comment]
@DAG1234567 the newer version of the wallet desktop (v0.20.1) has this fix. 

Closing the issue now.
