### ISSUE TITLE
Unable to generate a transaction in 0.20.0

### ISSUE THREAD

**Issue by jeefuji** [HathorNetwork/hathor-wallet#236]
Version : 0.20.0
Environment : Mainnet
Wallet type : Software

![image](https://user-images.githubusercontent.com/2582540/134591500-50bb5d83-eeee-4b9b-959f-87bcb84346d7.png)

Trying to generate a transaction (1HTR or 10HTR) in Hathor Wallet 0.20.0 on mainnet, and I'm blessed with an error "Error: "list" argument must be an Array of Buffers".
This error has been only witnessed on a software wallet, because I wasn't able yet to test it on an hardware wallet.

It happen just after entering my PIN code.

**Comment by pedroferreira1** [comment]
Hi @jeefuji , the version v0.20.0 had a build problem. We've release v0.20.1 with the fix and it's working fine. Thanks for the report.

Closing the issue.

**Comment by wwaayyaa** [comment]
@pedroferreira1 
Hello, the current latest code I use is 0.22, the system is macOS
The compiled desktop version will also report an error when sending a transaction:
Error: "list" argument must be an Array of Buffers
