### ISSUE TITLE
Cannot open ledger while Hathor App is open 

### ISSUE THREAD

**Issue by JohnnyRotton1** [HathorNetwork/hathor-wallet#253]
I am having problems transferring my Hathor to Ledger Nano s. I have downloaded the Hathor app for my ledger and when the Hathor app advises to open the app on the Nano it disconnects me from ledger live. Any suggestions

**Comment by pedroferreira1** [comment]
Can you confirm both your ledger firmware and ledger live are in the latest versions?

**Comment by JohnnyRotton1** [comment]
Hi, yes, both ledger nano and live are up to date. Just double checked now

Thanks

**Comment by JohnnyRotton1** [comment]
Hi Pedro,

Thanks, its resolved now. Do the tokens show up on ledger live or just
within the Hathor Wallet app on my desktop?



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pedroferreira1** [comment]
>  Do the tokens show up on ledger live or just within the Hathor Wallet app on my desktop?

Just on the desktop wallet.
