### ISSUE TITLE
NFTs not showing up in wallet

### ISSUE THREAD

**Issue by StephenJCrosby** [HathorNetwork/hathor-wallet#254]
Hi, I just purchased an NFT Anubian #120 my name is Stephen Crosby. I have a Hathor wallet and I can see the Anubian #120 UID in my wallet and registered the NFT. However, it is not showing up in my NFTs section. Can you please send me an e-mail at sjcrosby11@gmail.com to help me with this issue. As I would like to have my registered NFT in my NFTs section as well as my wallet so I can actually see the artwork I purchased. Please help. Thank you for you time. Screenshots attached. Sincerely, Stephen
<img width="979" alt="Screen Shot 2021-12-09 at 1 34 30 AM" src="https://user-images.githubusercontent.com/95843616/145346151-7da8d4f9-d962-44a5-888d-1347861cde03.png">
<img width="994" alt="Screen Shot 2021-12-09 at 1 34 40 AM" src="https://user-images.githubusercontent.com/95843616/145346193-7096cf5a-f591-44c9-a490-13e15ccaec07.png">

**Comment by pedroferreira1** [comment]
@StephenJCrosby if you go to the "Balance & History" tab do you see your balance correctly?

Can you share the token uid here please?

**Comment by StephenJCrosby** [comment]
Hi Pedro, this is what it looks like on my Balance & History tab. It says balance 0.01 A120 but I purchased the A120 for 359 HTR. Please see screenshots attached. And my UID is 00000000dfd5d94e4f0e9a34ff79edeec358e003e2858435ea6ded1131bd189a

I still cannot see my NFT in the NFTs section, please see screenshots. Please help. Thank you very much. Sincerely, Stephen
<img width="989" alt="Screen Shot 2021-12-09 at 8 22 20 PM" src="https://user-images.githubusercontent.com/95843616/145501345-3b7f67dd-cf20-472f-88a4-42a09fb86a65.png">
<img width="999" alt="Screen Shot 2021-12-09 at 8 22 28 PM" src="https://user-images.githubusercontent.com/95843616/145501379-7ed50cd5-3b76-45ea-9cd0-107a8311a038.png">
<img width="993" alt="Screen Shot 2021-12-09 at 8 22 09 PM" src="https://user-images.githubusercontent.com/95843616/145501407-244a742f-18f3-4b78-be0f-52aa7b6a72d5.png">

**Comment by pedroferreira1** [comment]
@StephenJCrosby your NFT is fine but the image is under review by our team. It should show up soon when it's reviewed.

**Comment by StephenJCrosby** [comment]
Hi Pedro, could you please let me know why my NFT is being reviewed? As I did register the token. As did my friend with his an it was in his NFTs immediately. And could you please give me a time estimate of approximately how long I should wait before I expect to see my A120 NFT under my NFTs in my Hathor Wallet? I purchased this NFT as a gift for someone who's birthday is coming up soon and I would really like to be able to show them the artwork I purchased. Also, are there any other steps I need to take or do I need to follow up if it is not in my wallet before the end of the week? I just do really need to be able to see the artwork, as it was purchased as a gift for an artist who's birthday is next Monday. Any more information or help on this would really be greatly appreciated. Thank you ever so kindly and have a great day today! Sincerely, Stephen Crosby
<img width="998" alt="Screen Shot 2021-12-12 at 8 13 51 PM" src="https://user-images.githubusercontent.com/95843616/145738121-23f4414d-1c61-4ee4-be24-e1bac7983050.png">
<img width="1004" alt="Screen Shot 2021-12-12 at 8 14 01 PM" src="https://user-images.githubusercontent.com/95843616/145738127-bbcf59aa-6fa8-47b5-80f9-0b96818cbc5c.png">
