### ISSUE TITLE
How to sell properly on Hathor?

### ISSUE THREAD

**Issue by StephenJCrosby** [HathorNetwork/hathor-wallet#255]
Hi, I'm trying to sell my NFT on Hathor but I want to make sure I do it properly. Can you please tell me the steps on how to send my NFT token to the right address? Do I enter the price I want to list it for? Or do I send what it currently states in my wallet, which is 0.01? Please see screenshot attached. I just want to make sure I do this properly before I list my NFT for sale. Please help. And thanks! Stephen
<img width="1258" alt="Screen Shot 2021-12-09 at 2 09 29 AM" src="https://user-images.githubusercontent.com/95843616/145350943-0905d343-97e7-4517-9d44-6f8b3afcfbc6.png">

**Comment by pedroferreira1** [comment]
Hathor Marketplace is not managed by Hathor team. You should get in touch with their team.

**Comment by StephenJCrosby** [comment]
Hi Pedro, how do I contact the Hathor Marketplace team? I have been looking everywhere on Google and can't find their contact information. Could you please help me find their contact information to contact them with this inquiry? Thank you, sincerely, Stephen.
