### ISSUE TITLE
I'm stucked with my NTFs on my ledger

### ISSUE THREAD

**Issue by beirao** [HathorNetwork/hathor-wallet#260]
Hi, 

I bought a lot of NFTs but I have just realise that I can not send NFTs on my ledger. So I can't sell my NFTs. 
When custom token sending will be able on ledger ?

Best regards.

![image](https://user-images.githubusercontent.com/36646641/147128439-bd1c24c0-e9be-43f9-b5ea-4e754532f2c3.png)

**Comment by beirao** [comment]
> I bought a lot of NFTs but I have just realise that I can not send NFTs on my ledger. So I can't sell my NFTs. When custom token sending will be able on ledger ?

From my ledger*

**Comment by luislhl** [comment]
Support for this is under development right now, a release will be made soon for the Ledger app and Hathor Wallet.

However, some additional time will be needed after this for the Ledger app to go through Ledger's review.

Keep an eye on announcements that will be made when everything is in place.
