### ISSUE TITLE
Check version compatibility error

### ISSUE THREAD

**Issue by pedroalvesbatista** [HathorNetwork/hathor-wallet#29]
Running the `npm start` on `node 12.0.0` raises a series of errors.

**Comment by obiyankenobi** [comment]
@pedroalvesbatista Can you add a log of the errors? This way we can check if we are able to reproduce it.

**Comment by obiyankenobi** [comment]
I had no problem running a fresh install on `node v12.11.1` (macOS 10.14.6). Ran `npm install` + `npm start`.

Will close this issue until we have more information the problem really exists.
