### ISSUE TITLE
There is an urgent need for a functional and stable wallet！！！

### ISSUE THREAD

**Issue by wwaayyaa** [HathorNetwork/hathor-wallet#290]
After using the official wallet for a while, my experience was very bad.

First of all, this is a block reward wallet. As the version is constantly updated, the amount I can transfer is getting smaller and smaller. On the one hand, it is the limit of the number of inputs. On the other hand, after there are too many transfers, an unknown error will be reported if the transferred amount is greater than 1808, so I can only transfer 1800 at a time.

Second, the loading process of more than 200,000 transaction records takes a long time, and it takes about 20 minutes to open the wallet each time. If I accidentally lock the screen, or the network is unstable, or the server rejects the request, the loading progress starts from 0 again.

Third, I am a developer, I hope to have such an API, I only need to provide the address, amount, and password to easily complete the transfer, but I can't find it.

Fourth, I now have hundreds of thousands of HTR stuck in my wallet. I can only do it manually. Due to the large number of transactions, it takes about 2 minutes after each transfer is completed. Notice! I can only transfer 1800HTR at one time.

Fifth, I thought of changing the code of the wallet so that it can automatically run the operations I want. As a result, I encountered an error in the 0.22 transfer. I found that you fixed it in 0.20.1, but I actually encountered it in 0.22, so I wasted a lot of time and had to go to 0.20.1 to complete my transfer.

Sixth, sometimes the balance is incorrect, and it shows that I only have 400. After I transfer 400, it shows that I have 1,000. After I transfer 1,000, it shows all my balance correctly.

Seventh, although I tried to change the code of my wallet so that he can transfer money semi-automatically, due to problems 1, 2, 4, and 6, my wallet can only complete the transfer normally in a very short period of time. Most of the time reloading or error "Insufficient"! ! ! !

**Comment by D45putspin** [comment]
theres a api, https://wallet-headless.docs.hathor.network/#/paths/~1wallet~1simple-send-tx/post

**Comment by wwaayyaa** [comment]
I watched hathor-core, hathor-wallet, hathor-wallet-lib several projects, the only thing I didn't notice was this one.
I hope you can solve some of the above problems, so that non-developers can operate by themselves.

**Comment by D45putspin** [comment]
im not part of team just recieved this in my email and answered ahah they are working on a new wallet asfar as i know

**Comment by pedroferreira1** [comment]
@wwaayyaa thanks for the report. Most of your problems happen because of the number of transactions in your wallet. Nowadays the wallet needs to load all transactions that belong to it from the full node to get your full balance and your utxos, so the more transactions you have, the longer it takes to fully load it. We are in the final phase of development of a new service that will allow users to load their wallets in a few seconds, even with millions of transactions.

Can I invite you for our rollout testing when we start doing it? Would be great for us to understand how fast the wallet will become with 200k+ transactions.

The wallet headless shared by @D45putspin will allow you to execute actions using an HTTP API, however the time for load will probably be the same.

**Comment by wwaayyaa** [comment]
It was great to hear that and I would love to be involved in testing the new wallet.
Then I will wait and look forward to the arrival of the new wallet.

**Comment by wwaayyaa** [comment]
@D45putspin Sorry, thank you very much.

**Comment by andreabadesso** [comment]
Hi @wwaayyaa, can I add your public Github email (357466524@qq.com) to the rollout mail list?

**Comment by wwaayyaa** [comment]
@andreabadesso ok

**Comment by wwaayyaa** [comment]
@andreabadesso Sorry to reply you only today, I would like to ask when the new wallet is expected to be available?

**Comment by wwaayyaa** [comment]
@andreabadesso Hi, is there any update on the new wallet?

**Comment by msbrogli** [comment]
Hi @wwaayyaa . We've been testing it internally and make adjustments. I feel we should be able to add you to the test in the next 15 days. Trond should reach out to you soon.

**Comment by trondbjoroy** [comment]
Hi @wwaayyaa, the new wallet can only be tested on mobile for now. If you would like to test it, please find and copy your unique app identifier on the settings page in the mobile wallet and email it to trond@hathor.network

**Comment by wwaayyaa** [comment]
Under some of the previous constraints, I ran the code carefully after changing the code, and it was normal for a while. Also forgot about this issue.
Until today, the problem occurred again, and 1htr could not be transferred out, and the prompt "An unexpected error happened. Please try to send your transaction again."

Is the new wallet available now? Or is it still in beta?

**Comment by pedroferreira1** [comment]
@wwaayyaa we are still running some more tests, however your problem might be because of an old wallet version. Which version are you using?

If you upgrade your wallet and keep having problem, please let me know.

Note: make sure you have your wallet properly backed up before upgrading it.

**Comment by wwaayyaa** [comment]
> @wwaayyaa we are still running some more tests, however your problem might be because of an old wallet version. Which version are you using?
> 
> If you upgrade your wallet and keep having problem, please let me know.
> 
> Note: make sure you have your wallet properly backed up before upgrading it.

upgrade to 0.24.0 and solved my problem.
thanks, hope the new wallet will be released soon.
