### ISSUE TITLE
[Design] Atomic Swap

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-wallet#308]
# Summary

Atomic swap is a feature where two different wallets can swap tokens in a single operation without any third party or trust between wallet owners.

This expression is also known in the crypto world as exchanging different tokens from different chains, i.e. a cross-chain atomic swap.
Here in this design we will describe all operations only inside Hathor Network, swapping tokens created in the network.

# Motivation

Hathor Network already supports atomic swap by design in the protocol, however with the growth of the NFT market we have already seen some use cases asking about this feature.
Although this is supported in the protocol, having an easy-to-use UI/UX in our wallet would increase trust when swapping tokens, given that it can be done without trusting the other side of the transaction and without any third party.

# Acceptance criteria

We must have a way for our users to swap tokens in a single transaction without trust between parties and any third party.

# Guide-level explanation

### Atomic swap in Hathor

As stated before Hathor Network already supports atomic swap by design, it does this by allowing inputs from different owners and outputs to different addresses, both with multiple tokens all in the same transaction.
This way we only need to provide Alice and Bob with a way to coordinate the transaction so they can sign the inputs they own and the transaction can be propagated.

This design only contemplates the wallet headless, we will not design any UI/UX for the desktop and mobile wallets but the low-level will not block future implementations of atomic swap in other wallets.

### Atomic swap in our wallet headless

This design will describe a solution for coordination between Alice and Bob.
The solution allows multiple participants but for simplicity we will only describe the interactions with 2 participants i.e. Alice and Bob.

Swapping tokens is usually done by marketplaces and the OTC transactions are not very common (even with an easy-to-use UI, swapping inside a marketplace is even easier not only the UI/UX but mostly the match buyer<>seller).

The solution requires that users start a partial transaction and exchange the transaction data until it's completed.
This is done without any backend so the users can use any means to exchange the data (chat messages, a service, etc.).
The flow in this case would be the following with Alice and Bob exchanging tokens:

1. Alice and Bob agree in terms of the tokens and amount that will be swapped, e.g. 10 TKN1 (Alice) <-> 20 TKN2 (Bob)
1. Alice will start a new atomic swap in her wallet where she sends 10TKN1 and receives 20TKN2.
    1. The wallet will complete with the inputs she wants to send and outputs she wants to receive (and any change output for her inputs if needed).
    1. The wallet will then generate a string with the partial transaction to be copied, then Alice will send this data to Bob.
1. Bob will receive Alice's partial transaction data and will send it to his wallet along with any changes he wishes to make (i.e. send 20TKN2 and receive 10TKN1).
    1. If Alice inputs contains more than 10 TKN1 (e.g. 15 TKN1) the partial transaction will come with the change output (e.g. 5 TKN1 to Alice).
    1. Bob's wallet will complete the transaction with his inputs and outputs and will generate another partial transaction data to be sent to Alice
1. If Alice thinks that the transaction is complete and the output funds match the input's then Alice can send the data to create a transaction and sign the data.
    1. The data returned here contains the transaction and signatures which will be sent to Bob.
1. If Bob agrees that the transaction is complete he can also sign the transaction.
    - If the data for all inputs are accounted for Bob can complete the transaction with the weight, timestamp and input data then send to the transaction mining service.
    - If Bob tries to change any transaction information, e.g. an output address, the transaction will be rejected since Alice's signature signed the transaction data she agreed to.
    - If Bob wishes to change any detail he can do so (invalidating the signatures sent by Alice) and send the information to Alice so they can start over.
1. Transaction is mined, parents are added and then it's propagated to the network.

**Upsides:**

1. Easy to implement.
3. We never store anything related to the swap on Hathor servers, then there should be no legal problem.

**Downsides:**

1. Exchanging large hexadecimal strings is not easy for "normal" users.
2. There is no automatic feedback from the wallet about the operation.

# Reference-level explanation

###  Encoded data to be passed by participants

There are 2 types of data that will be passed among participants, the transaction data and the signatures data.
Both data types will be managed by a model:
- Transaction data will be called `PartialTx`;
- Signatures data (or input data) will be called `PartialTxInputData` ;

#### PartialTx

This class will hold the partial data and construct the information to be passed among participants.

An instance will hold:
- a list of inputs (tx_id, index, token, value).
  - The token and value are necessary because the tx may not be from our wallet.
- a list of outputs (value, address, token, isChange).

*Method `getTxData`*: Will return an object with the calculated transaction data to be used on other helper functions of the wallet-lib.

*Method `getTx`*: Will return an instance of the transaction model with the partial data.

*Method `isComplete`*: Will return `true` if the total sum of funds of the inputs match the funds from the outputs (for all tokens).

*Method `addInput`*: Add a new input on the local data, may need to fetch the transaction to save the token and value of the input.

*Method `addOutput`*: Add a new output on the local data.

*Method `serialize`*: Will build the partial transaction from the inputs and outputs into a json string and return the hex encoding of it.

`PartialTx|<txHex>|<changeOutputIndex0>|<changeOutputIndex1>`

*Method `deserialize`*: Class method that will read the hex encoded string and return an instance of `PartialTx`.

```js
const data = serialized.split('|');
// data[0] must be 'PartialTx'
// data[1] is the transaction hex
const txHex = data[1];
// data from 2 onwards are the change output indices
const changeOutputs = data.slice(2).map(x => +x);
```
We should have a custom error to throw if the `deserialize` method fails so the wallet can show a user friendly message.
The errors that can happen are:
- Invalid prefix.
- txHex or `data[1]` is not a valid transaction.
- change outputs on the array are anything other than numbers.

#### PartialTxInputData

This class will hold the input data for a partial tx and construct the data to be passed among participants.

An instance will hold:
- a `Record<number, Buffer>` (key will be input index and value input data hex encoded).
- an identifier for the partial tx (i.e. the data to sign hash)
- the length of the input array so we know when we have all input datas.

*Method `addData`*: Will receive the input index and input data and add it to the record.

*Method `isComplete`*: Will return `true` if the length of input data the instance holds is equal to the length of inputs from the tx proposal data.

*Method `serialize`*: WIll build a string with all input data and indexes in the format below.

`PartialTxInputData|<txIdentifier>|<index0>:<input0DataHex>|<index1>:<input1DataHex>|<index2>:<input2DataHex>`

Obs: This method does not need the signatures to be complete.

*Method `addSignatures`*: Will parse the serialized data and add it to the local record.
If the `txIdentifier` from the parsed data does not match the local `txIdentifier` we should throw an exception.

#### Create input data

The `transaction.prepareData(data, pin, options)` method can be used to sign the inputs the loaded wallet owns.

Multisig or P2SH wallets can also participate on an atomic swap.
The process to generate the input data will be done with other APIs not comtemplated on this design.

#### PartialTxProposal

This facade will manage an instance of `PartialTx` and `PartialTxInputData` with the purpose of generating a complete `Transaction` instance with all signatures.

```js
interface PartialTxProposal {
    partialTx: PartialTx;
    signatures?: PartialTxInputData; // may be null before we are ready to sign the transaction.
    data?: Object; // transaction data used to create the data to sign
    transaction?: Transaction;

    static setData(string); // create and instance of PartialTxProposal from the serialized data.

    addSend(token: string, value: number); // chooses inputs and adds change output if needed
    addReceive(token: string, value: number, { timelock: number|null }); // Adds outputs with these tokens to our wallet address

    addInput(tx_id: string, index: number); // chooses inputs and adds change output if needed
    addOutput(token: string, value: number, address: string, {timelock: number|null, isChange: Boolean}); // Adds an output to the address of the token specified

    isComplete(); // return if we are ready to build the transaction

    signData(pin); // Builds the data and signs the inputs from the loaded wallet, any changes to the partial data should invalidate this generated signatures.
    resetSignatures(); // sets the signatures to null.

    prepareTx(); // Builds the transaction and return it.
}
```

Any method that may change the partial tx must call `resetSignatures` so we don't hold signatures to a transaction that has changed.

### POST,PUT /wallet/atomic-swap/tx-proposal

Create a new atomic swap or update an ongoing one.

Request:
- Content-Type: application/json
- Body:
  - inputs
    - Description: an array of input objects
    - Example: `[{"hash": "00abc...", "index": 0}]`
    - Type: Array of objects
  - outputs
    - Description: an array of output objects
    - Example: `[{"token": "00123abc...", "value":100, "address": "HSQN5abc..."}]`
    - Type: Array of objects
  - send_tokens
    - Description: Choose inputs to send the amount of tokens without a corresponding output receiving (may add change)
    - Example: `[{"token": "00123abc...", "value":100}]`
    - Type: Array of objects
  - receive_tokens
    - Description: Add outputs receiving tokens to an address from the wallet.
    - Example: `[{"token": "00123abc...", "value":100}]`
    - Type: Array of objects
  - change_address
    - Description: Use this address as change address (only works with `send_tokens`)
    - Example: `"HSQN5abc..."`
    - Type: string
  - partial_tx
    - Description: The current state of the atomic swap
    - If not present will create a new atomic swap from the other arguments
    - Type: string
  - lock
    - Description: If the UTXOs on the returned partial transaction should be marked as `selected_as_input`
    - Type: boolean

OBS: All body arguments are optional but at least one of [`inputs`, `outputs`, `send_tokens`, `receive_tokens`] is required.

Response:
- Content-Type: application/json
- Body:
  - data: the string with the serialized `PartialTx`
  - isComplete: If the funds from inputs match the outputs

### Sign and push operations

We will update the routes:

- `/wallet/tx-proposal/get-my-signatures` to `/wallet/p2sh/tx-proposal/get-my-signatures`
- `/wallet/tx-proposal/sign` to `/wallet/p2sh/tx-proposal/sign`
- `/wallet/tx-proposal/sign-and-push` to `/wallet/p2sh/tx-proposal/sign-and-push`

Since these routes use P2SH exclusive methods we should specify this as to not generate confusion.

Other routes will be created:

- `/wallet/atomic-swap/tx-proposal/get-my-signatures`
- `/wallet/atomic-swap/tx-proposal/sign`
- `/wallet/atomic-swap/tx-proposal/sign-and-push`

These will have similar functionalities but using `PartialTxInputData` instead of `P2SHSignatures` and `PartialTx` instead of the transaction hex where applicable.

### POST /wallet/decode

The `decode` API will be updated to also accept an optional `partialTx` parameter with the serialized `PartialTx`.
If `partialTx` is sent instead of `txHex` we will add the transaction hex from the partial data to the response.
If both `partialTx` and `txHex` are sent on the request, the response will only consider the `txHex`.

This method should be used to check the current state of the atomic swap but it will also double as a way to extract the transaction hex.
The transaction hex will be used by MultiSig wallets to sign the transaction.

### POST /wallet/p2sh/tx-proposal/get-input-data

This route will be used to extract the input data from a transaction hex and return a serialized `PartialTxInputData`.

Request:
- Content-Type: application/json
- Body:
  - txHex
    - Description: Transaction hex
    - Example: `000abcdef1234567....00abc`

Response:
- Content-Type: text
- Body: A string with the serialized `PartialTxInputData`.

This method can be used by MultiSig wallets to convert their signatures into the atomic swap compliant format.

### POST /wallet/atomic-swap/tx-proposal/unlock

Unmark any UTXOs marked as `selected_as_input` on the body.

Request:
- Content-Type: application/json
- Body:
  - txHex
    - Description: transaction hex
    - Type: string
  - partialData
    - Description: Serialized partial data
    - Type: string

Reponse:
- Content-Type: application/json
- Body:
    - success: `{"success": true}`
    - fail: `{"success": false, "error": "error message"}`

### GET /wallet/atomic-swap/tx-proposal/get-locked-utxos

List all UTXOs marked as `selected_as_input`.

Reponse:
- Content-Type: application/json
- Body: A json encoded list of all UTXOs marked as `selected_as_input`

# Future possibilities

## tx proposal routes

We are currently splitting the functions of signatures apis between atomic and p2sh because they are currently not compatible.
There could be some confusion if we created a second set of sign/push APIs without specifying what each one is related to.

In the future we may merge these APIs to simplify the use of both functionalities.

# Rationale and alternatives

Another solution is a bit more complex but has an intuitive UI/UX for both users.
The idea is to have a central database that will store metadata of each swap and a backend to return information about them.
The flow in this case would be the following with Alice and Bob exchanging tokens:

1. Alice and Bob agree in terms of the tokens and amount that will be swapped, e.g. 10 TKN1 <-> 20 TKN2 (same as the first solution)
1. Alice will start a new atomic swap in her wallet and the backend creates an id for the swap which Alice sends to the other participants.
1. All other participants (in this case Bob) join the swap with the id sent by Alice.
1. Each participant can add inputs and outputs, every change will be sent to the backend
    - Every change will be communicated to the other participants with an api on their end, which polls for the atomic swap state.
1. Alice can then accept a transaction by sending the signature to the backend.
    - This will only be available if the input funds match the output funds.
1. When all participants have signed the backend can send the transaction to the transaction mining service and notify the users the the transaction is being mined.
1. The wallets can either exit and wait for the transaction to arive or poll the transaction mining service for the status.

Note: we would need a timeout on the swap id so we don't keep data that is never completed forever.

**Upsides:**

1. No need to exchange large hex strings.
2. Automatic feedback in the wallet about the operation.

**Downsides:**

1. We need to create a backend + database to store this metadata.
2. We might have legal problems if we store swap information.

# Prior art

### Hash Timelock Contract Technology (HTCL)

Cross chain atomic swap nowadays uses HTCL contracts, which is a smart contract that locks a transaction until both parties validate it, i.e. the tokens you deposit in the contract address will only be swapped when the tx is "approved".
If the transaction is not validated until a timeout expires, both parties receive their tokens back.

The basics of an atomic swap between Alice and Bob is:

1. Alice deposits her tokens in the contract address, which can only be unlocked with a key that she has access.
2. Alice shares a hash of this key with Bob and he deposits his tokens in an address created with this hash only if what Alice had deposited is correct.
3. Now that both tokens have been deposited, Alice can validate if the transaction is correct and use her key to unlock it and get her share of the swap.
4. Now that the transaction is unlocked, Bob can also get his share and the swap is completed.

The main goal with this section is not to go deep into the internals of how the contract works but to understand the flow that users are used to do to create an atomic swap.

Some [applications](https://liquality.io/atomic-swap-dapp.html) have already developed a kind of secondary market of swaps, so users don't need to do all those steps.

# Task breakdown

## Wallet-lib

- Create models for partial tx (1)
- Create PartialTxProposal facade and tests (2)
- Send a tx with the tx proposal facade between wallets (0.5)

## Wallet-Headless

- Change decode API (0.5)
- Create a p2sh router and move P2SH sign routes (0.2)
- Create a router for atomic swap inside the tx-proposal (0.1)
- Create the route `POST /wallet/atomic-swap/tx-proposal` (1)
- Create the sign routes on the atomic swap router (2)
- Create `/wallet/p2sh/tx-proposal/get-input-data` (0.2)
- Create `unlock` and `get-locked-utxos` endpoints (1)

**Comment by luislhl** [comment]
> I feel atomic swaps will be extremely useful for showing to use cases the possibilities but I believe it won't be widely used by our users inside our wallet.
Because of that I think we should go with the first (and simpler) solution, which in my opinion is not that bad for most users that will use this feature and, if we see this adoption, we can improve it later.

I agree with this. But how do you think we could monitor adoption so we know there is demand for an improvement?

> The first solution which is simple to implement requires that users start a partial transaction and exchange the transaction data until it's completed.

In the simple solution, we would require that Alice and Bob keep their wallets open until the operation is complete, right? I mean, it would be a synchronous operation between them, each needing to be online at the same time.

> Transaction data will be called TxProposalData;

We have some interfaces named `TxProposalCreateResponseData`, `TxProposalInputs` and `TxProposalOutputs`.

If this new one will be used only in the context of the Atomic Swap feature, should we name it with a more specific name?

**Comment by r4mmer** [comment]
> In the simple solution, we would require that Alice and Bob keep their wallets open until the operation is complete, right?

Not really, since the data being passed between alice and bob holds the entire transaction it can be used to "save the state" of the swap after the wallet is closed.
I think the main problem would be how to use the "state" received when the user inputs the data. This can get very complex so I think we should always overwrite the local state with the data and not try to merge them (e.g. i add some inputs then paste the data, the wallet would erase my inputs.)

> If this new one will be used only in the context of the Atomic Swap feature, should we name it with a more specific name?

You're right, having the wallet service tx proposal and the atomic swap tx proposal can be confusing.
I was thinking on changing to something like `PartialTx` and `PartialTxData` (data as in input data, i think signature was a bit misleading)

**Comment by r4mmer** [comment]
> The serialized string might have a prefix to identify what it is related to (e.g., AtomicSwapPartialTx:[data-comes-here]).

I'll add the prefix.

> It seems PartialTxProposal.setData(...) should be a class method that will return a PartialTxProposal object.

I was thinking of a method to overwrite the local data, but making it a method that returns a proposal seems more intuitive.

> After creating a PartialTxProposal using setData, how will we present the partialTx for the users, so they can review and confirm it follows the agreement?

The `proposalInstance.partialTx.inputs` and `proposalInstance.partialTx.outputs` should have all information we would need to show the summary.

>  Should we block the UTXO's picked by Alice and Bob? For how long? If the whole flow takes a while, Alice or Bob might use these UTXOs on other transactions.

This can be an issue since the user can exit the atomic swap screen without invalidating the inputs chosen on the swap.
I think we should have a long timer (longer than the current one on `sendTransaction` facade which is 60s), maybe have a 5min lock?

**Comment by msbrogli** [comment]
> This can be an issue since the user can exit the atomic swap screen without invalidating the inputs chosen on the swap.
I think we should have a long timer (longer than the current one on sendTransaction facade which is 60s), maybe have a 5min lock?

I feel we should discuss it further after the UX/UI is done. We might have different behaviors depending on how users are going to use this feature. Anyway, the design must cover the UTXO lock mechanism.

**Comment by pedroferreira1** [comment]
When I first thought about how to implement the atomic swap feature, I thought about using the same `Transaction` class to store everything we need. I feel we already have the possibility to do it and creating a new class just for that would be overwork. About the Input data I felt the same way. 

At first, I thought we would just build util methods to create the atomic swaps, i.e., having methods to get utxos from specific amount/token and create a change output if needed. Get a transaction object and add inputs/outputs. Get my inputs and sign them.

Is there any reason we can't use the current `Transaction` model class to do it?

> Anyway, the design must cover the UTXO lock mechanism.

I agree we should do it. We can have it done and configurable, then we can discuss further for how long and ways of unlocking them. Maybe we can have a screen of local atomic swaps that we save in the local storage.

**Comment by r4mmer** [comment]
> Is there any reason we can't use the current Transaction model class to do it?

There is not anything that blocks the use, the key reasons why I believe it would be better to have a separate class for this is the extra data we should add to make the atomic swap process easier for the user.

For the inputs we need to have the `token` and `value` because we may not own all utxos so it will not be on the transaction history (fetching the tx for each input everytime we want to calculate the balance does not seem optimal).
I also added the address the utxo belongs to because the `src/transaction.js:signTx` method requires the address to check if it's from the loaded wallet and sign. 

For the outputs, I believe the only metadata I added is the `isChange` (which could be nice to have for the UI/UX but not required) and the `token`, since the usual output uses the `tokenData` that "points" to a position on the tokens array which in turn is mutable the whole process up to when we create the transaction to sign it.
So using `tokenData` and the output model creates the need to iterate on all outputs to check the `tokenData` whenever we remove any input or output from the transaction because the positions on the token array could have changed.

If we can still make the process smooth for the developer and UI/UX with the transaction model then i guess we should, but I believe it will be more taxing than having an atomic swap facade for this.

> I agree we should do it. We can have it done and configurable, then we can discuss further for how long and ways of unlocking them. Maybe we can have a screen of local atomic swaps that we save in the local storage.

Since the atomic swap "negotiation" process can take from seconds to days it's very unlikely we can do a normal timeout for this locks. I think having these atomic swaps saved on the localStorage is the best approach, if the user wants to "free" the inputs he can delete it and we can check if an atomic swap is still valid by checking if any inputs are spent or voided.

**Comment by pedroferreira1** [comment]
> If we can still make the process smooth for the developer and UI/UX with the transaction model then i guess we should, but I believe it will be more taxing than having an atomic swap facade for this.

Yeah, I think it's possible to do with the transaction model but it's much better for meta information and UI/UX with the new custom classes.

> I think having these atomic swaps saved on the localStorage is the best approach, if the user wants to "free" the inputs he can delete it and we can check if an atomic swap is still valid by checking if any inputs are spent or voided.

We can discuss how to lock/unlock in the UI later but the design should have at least a small section to describe the localStorage solution.

**Comment by pedroferreira1** [comment]
I like the API descriptions, just some thoughts.

I feel using `atomic` in the endpoint may be misleading, I prefer using `atomic-swap`. What do you think?

> POST,PUT /wallet/tx-proposal/atomic

- `send_tokens`: maybe we should add an optional field in this object array with the `change_address`.
- `partial_tx`: this has to be `null` for POST and can't be `null` for PUT, right?
- `lock`: why the user will be able to select this?

> Sign and push operations

- Updating the routes endpoint is not that easy, we will need to add breaking changes because of it. Why don't we already change those routes before releasing multisig? But even better, we could add a type in the URL (or in the body parameter) with the type, then we use only one endpoint. What do you think?

> POST /wallet/tx-proposal/atomic/extract-input-data

I think I prefer `/get-input-data` but I'm okay with extract as well.

> Unlock

Should we have also an API to return the locked utxos?

**Comment by r4mmer** [comment]
> - `lock`: why the user will be able to select this?

I think we should have this with default `false`, but the option to not lock any inputs would be great for development and for negotiations when the intent is not to complete the transaction (i.e. simulations).

> Updating the routes endpoint is not that easy, we will need to add breaking changes because of it. Why don't we already change those routes before releasing multisig? But even better, we could add a type in the URL (or in the body parameter) with the type, then we use only one endpoint. What do you think?

We changed the routes for multisig before release and now  we can safely create the `/wallet/atomic-swap` router.

Going forward I think we should try to merge both p2sh and atomic-swap routes, there are some minor details that if solved would enable us to use the same endpoints and the same behavior for both features.

> I think I prefer /get-input-data but I'm okay with extract as well.

I'll change this.

> Should we have also an API to return the locked utxos?

I'll add this api.

**Comment by r4mmer** [comment]
> Why the default false?

I'm sorry, I meant `true` but typed `false`. We should lock by default.

**Comment by msbrogli** [comment]
The overall design is approved to me. I'll add another comment with some suggestions for the wallet headless API.

**Comment by msbrogli** [comment]
I don't like having different APIs for multisig and atomic swaps. I feel we should have a tx-proposal API with multiple methods that can be used to modify the tx-proposal until it's ready. Of course some methods might fail if they do not make sense in a given context. Each tx proposal would also store metadata about that specific tx (e.g., metadata about multisig). Note that the metadata might be related to the transaction itself or to an input or output. This approach is supposed to give more flexibility to use cases and make our development easier.

Given this context, I feel that all APIs should be under the `/tx-proposal/` prefix, where multisig and atomic swaps might have their own sub-prefix (e.g., `/tx-proposal/atomic-swaps/` and `/tx-proposal/multisig`).

@r4mmer @pedroferreira1  What do you think?

**Comment by pedroferreira1** [comment]
I agree to create another project to solve those key issues and create a single endpoint. 

For me this design is approved.

**Comment by msbrogli** [comment]
I agree that we can do it in a separate project.

This design is approved for me.
