### ISSUE TITLE
Unable to send tokens. Getting "an unexpected error happened" message

### ISSUE THREAD

**Issue by BitcoinBasquiat** [HathorNetwork/hathor-wallet#463]
I am unable to send tokens using the desktop wallet using a mac. I get the following message "An unexpected error happened. Please try to send your transaction again."

I have tried multiple times again and the outcome has not changed. Here's a screenshot:
<img width="1019" alt="Screen Shot 2023-12-20 at 6 39 52 AM" src="https://github.com/HathorNetwork/hathor-wallet/assets/93584608/b3b19953-ba04-4ab8-9af8-64bea4243f48">

**Comment by pedroferreira1** [comment]
You should use the latest version of the wallet to send your tokens.

Before upgrading, make sure you have your seed properly backed up. If you don't have it, get in touch with one of the community manager to advise you on how to make it work.
