### ISSUE TITLE
Wallet initial size can cut off some elements

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-wallet#90]
On my Mac:
![image](https://user-images.githubusercontent.com/3236756/74592685-0881f200-5024-11ea-803f-53a151299aed.png)

Community user Farpa:
![image](https://user-images.githubusercontent.com/3236756/74592691-1a639500-5024-11ea-96d6-0f1ae2713e94.png)

**Comment by its-tayo** [comment]
Hi @obiyankenobi can I have a go at this please?

**Comment by obiyankenobi** [comment]
> Hi @obiyankenobi can I have a go at this please?

Sure @its-tayo , go ahead!

**Comment by its-tayo** [comment]
Thanks @obiyankenobi, I'll look at the code base later today then submit a pr.

**Comment by thr0wn** [comment]
Closed by #159
